/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/activities": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.activities.id"];
          created_at?: parameters["rowFilter.activities.created_at"];
          environment?: parameters["rowFilter.activities.environment"];
          description?: parameters["rowFilter.activities.description"];
          amountOfPlayers?: parameters["rowFilter.activities.amountOfPlayers"];
          activityWinner?: parameters["rowFilter.activities.activityWinner"];
          activityLoser?: parameters["rowFilter.activities.activityLoser"];
          killCounts?: parameters["rowFilter.activities.killCounts"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["activities"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** activities */
          activities?: definitions["activities"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.activities.id"];
          created_at?: parameters["rowFilter.activities.created_at"];
          environment?: parameters["rowFilter.activities.environment"];
          description?: parameters["rowFilter.activities.description"];
          amountOfPlayers?: parameters["rowFilter.activities.amountOfPlayers"];
          activityWinner?: parameters["rowFilter.activities.activityWinner"];
          activityLoser?: parameters["rowFilter.activities.activityLoser"];
          killCounts?: parameters["rowFilter.activities.killCounts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.activities.id"];
          created_at?: parameters["rowFilter.activities.created_at"];
          environment?: parameters["rowFilter.activities.environment"];
          description?: parameters["rowFilter.activities.description"];
          amountOfPlayers?: parameters["rowFilter.activities.amountOfPlayers"];
          activityWinner?: parameters["rowFilter.activities.activityWinner"];
          activityLoser?: parameters["rowFilter.activities.activityLoser"];
          killCounts?: parameters["rowFilter.activities.killCounts"];
        };
        body: {
          /** activities */
          activities?: definitions["activities"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/payouts": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.payouts.id"];
          created_at?: parameters["rowFilter.payouts.created_at"];
          public_address?: parameters["rowFilter.payouts.public_address"];
          payment_amount?: parameters["rowFilter.payouts.payment_amount"];
          payment_token_symbol?: parameters["rowFilter.payouts.payment_token_symbol"];
          payment_token_address?: parameters["rowFilter.payouts.payment_token_address"];
          room_id?: parameters["rowFilter.payouts.room_id"];
          notes?: parameters["rowFilter.payouts.notes"];
          reason?: parameters["rowFilter.payouts.reason"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["payouts"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** payouts */
          payouts?: definitions["payouts"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.payouts.id"];
          created_at?: parameters["rowFilter.payouts.created_at"];
          public_address?: parameters["rowFilter.payouts.public_address"];
          payment_amount?: parameters["rowFilter.payouts.payment_amount"];
          payment_token_symbol?: parameters["rowFilter.payouts.payment_token_symbol"];
          payment_token_address?: parameters["rowFilter.payouts.payment_token_address"];
          room_id?: parameters["rowFilter.payouts.room_id"];
          notes?: parameters["rowFilter.payouts.notes"];
          reason?: parameters["rowFilter.payouts.reason"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.payouts.id"];
          created_at?: parameters["rowFilter.payouts.created_at"];
          public_address?: parameters["rowFilter.payouts.public_address"];
          payment_amount?: parameters["rowFilter.payouts.payment_amount"];
          payment_token_symbol?: parameters["rowFilter.payouts.payment_token_symbol"];
          payment_token_address?: parameters["rowFilter.payouts.payment_token_address"];
          room_id?: parameters["rowFilter.payouts.room_id"];
          notes?: parameters["rowFilter.payouts.notes"];
          reason?: parameters["rowFilter.payouts.reason"];
        };
        body: {
          /** payouts */
          payouts?: definitions["payouts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/players": {
    get: {
      parameters: {
        query: {
          room_id?: parameters["rowFilter.players.room_id"];
          slug?: parameters["rowFilter.players.slug"];
          player?: parameters["rowFilter.players.player"];
          time_joined?: parameters["rowFilter.players.time_joined"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["players"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** players */
          players?: definitions["players"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          room_id?: parameters["rowFilter.players.room_id"];
          slug?: parameters["rowFilter.players.slug"];
          player?: parameters["rowFilter.players.player"];
          time_joined?: parameters["rowFilter.players.time_joined"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          room_id?: parameters["rowFilter.players.room_id"];
          slug?: parameters["rowFilter.players.slug"];
          player?: parameters["rowFilter.players.player"];
          time_joined?: parameters["rowFilter.players.time_joined"];
        };
        body: {
          /** players */
          players?: definitions["players"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/room_params": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.room_params.id"];
          /** Public Address of creator */
          created_by?: parameters["rowFilter.room_params.created_by"];
          slug?: parameters["rowFilter.room_params.slug"];
          /** Network rpc where contract lives */
          network?: parameters["rowFilter.room_params.network"];
          /** Address where the alt split rewards should be sent. */
          alt_split_address?: parameters["rowFilter.room_params.alt_split_address"];
          /** Contract address of the payment token */
          contract_address?: parameters["rowFilter.room_params.contract_address"];
          /** Token cost in order to enter the game */
          entry_fee?: parameters["rowFilter.room_params.entry_fee"];
          /** Chance that a PvE event will occur */
          pve_chance?: parameters["rowFilter.room_params.pve_chance"];
          /** Chance that a revive event will occur */
          revive_chance?: parameters["rowFilter.room_params.revive_chance"];
          /** Total prize split for kills in the game */
          prize_kills?: parameters["rowFilter.room_params.prize_kills"];
          /** Total prize split designated to go to the alternate address. */
          prize_alt_split?: parameters["rowFilter.room_params.prize_alt_split"];
          /** Total prize split for the game winner */
          prize_first?: parameters["rowFilter.room_params.prize_first"];
          /** Total prize split for 2nd place */
          prize_second?: parameters["rowFilter.room_params.prize_second"];
          /** Total prize split for third place */
          prize_third?: parameters["rowFilter.room_params.prize_third"];
          /** Total prize split designated for the developers of Rumble Raffle */
          prize_creator?: parameters["rowFilter.room_params.prize_creator"];
          created_at?: parameters["rowFilter.room_params.created_at"];
          updated_at?: parameters["rowFilter.room_params.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["room_params"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** room_params */
          room_params?: definitions["room_params"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.room_params.id"];
          /** Public Address of creator */
          created_by?: parameters["rowFilter.room_params.created_by"];
          slug?: parameters["rowFilter.room_params.slug"];
          /** Network rpc where contract lives */
          network?: parameters["rowFilter.room_params.network"];
          /** Address where the alt split rewards should be sent. */
          alt_split_address?: parameters["rowFilter.room_params.alt_split_address"];
          /** Contract address of the payment token */
          contract_address?: parameters["rowFilter.room_params.contract_address"];
          /** Token cost in order to enter the game */
          entry_fee?: parameters["rowFilter.room_params.entry_fee"];
          /** Chance that a PvE event will occur */
          pve_chance?: parameters["rowFilter.room_params.pve_chance"];
          /** Chance that a revive event will occur */
          revive_chance?: parameters["rowFilter.room_params.revive_chance"];
          /** Total prize split for kills in the game */
          prize_kills?: parameters["rowFilter.room_params.prize_kills"];
          /** Total prize split designated to go to the alternate address. */
          prize_alt_split?: parameters["rowFilter.room_params.prize_alt_split"];
          /** Total prize split for the game winner */
          prize_first?: parameters["rowFilter.room_params.prize_first"];
          /** Total prize split for 2nd place */
          prize_second?: parameters["rowFilter.room_params.prize_second"];
          /** Total prize split for third place */
          prize_third?: parameters["rowFilter.room_params.prize_third"];
          /** Total prize split designated for the developers of Rumble Raffle */
          prize_creator?: parameters["rowFilter.room_params.prize_creator"];
          created_at?: parameters["rowFilter.room_params.created_at"];
          updated_at?: parameters["rowFilter.room_params.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.room_params.id"];
          /** Public Address of creator */
          created_by?: parameters["rowFilter.room_params.created_by"];
          slug?: parameters["rowFilter.room_params.slug"];
          /** Network rpc where contract lives */
          network?: parameters["rowFilter.room_params.network"];
          /** Address where the alt split rewards should be sent. */
          alt_split_address?: parameters["rowFilter.room_params.alt_split_address"];
          /** Contract address of the payment token */
          contract_address?: parameters["rowFilter.room_params.contract_address"];
          /** Token cost in order to enter the game */
          entry_fee?: parameters["rowFilter.room_params.entry_fee"];
          /** Chance that a PvE event will occur */
          pve_chance?: parameters["rowFilter.room_params.pve_chance"];
          /** Chance that a revive event will occur */
          revive_chance?: parameters["rowFilter.room_params.revive_chance"];
          /** Total prize split for kills in the game */
          prize_kills?: parameters["rowFilter.room_params.prize_kills"];
          /** Total prize split designated to go to the alternate address. */
          prize_alt_split?: parameters["rowFilter.room_params.prize_alt_split"];
          /** Total prize split for the game winner */
          prize_first?: parameters["rowFilter.room_params.prize_first"];
          /** Total prize split for 2nd place */
          prize_second?: parameters["rowFilter.room_params.prize_second"];
          /** Total prize split for third place */
          prize_third?: parameters["rowFilter.room_params.prize_third"];
          /** Total prize split designated for the developers of Rumble Raffle */
          prize_creator?: parameters["rowFilter.room_params.prize_creator"];
          created_at?: parameters["rowFilter.room_params.created_at"];
          updated_at?: parameters["rowFilter.room_params.updated_at"];
        };
        body: {
          /** room_params */
          room_params?: definitions["room_params"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rooms": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rooms.id"];
          created_at?: parameters["rowFilter.rooms.created_at"];
          /** The room slug */
          slug?: parameters["rowFilter.rooms.slug"];
          params_id?: parameters["rowFilter.rooms.params_id"];
          created_by?: parameters["rowFilter.rooms.created_by"];
          game_started?: parameters["rowFilter.rooms.game_started"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rooms"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** rooms */
          rooms?: definitions["rooms"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rooms.id"];
          created_at?: parameters["rowFilter.rooms.created_at"];
          /** The room slug */
          slug?: parameters["rowFilter.rooms.slug"];
          params_id?: parameters["rowFilter.rooms.params_id"];
          created_by?: parameters["rowFilter.rooms.created_by"];
          game_started?: parameters["rowFilter.rooms.game_started"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rooms.id"];
          created_at?: parameters["rowFilter.rooms.created_at"];
          /** The room slug */
          slug?: parameters["rowFilter.rooms.slug"];
          params_id?: parameters["rowFilter.rooms.params_id"];
          created_by?: parameters["rowFilter.rooms.created_by"];
          game_started?: parameters["rowFilter.rooms.game_started"];
        };
        body: {
          /** rooms */
          rooms?: definitions["rooms"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          public_address?: parameters["rowFilter.users.public_address"];
          created_at?: parameters["rowFilter.users.created_at"];
          nonce?: parameters["rowFilter.users.nonce"];
          id?: parameters["rowFilter.users.id"];
          name?: parameters["rowFilter.users.name"];
          updated_at?: parameters["rowFilter.users.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions["users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          public_address?: parameters["rowFilter.users.public_address"];
          created_at?: parameters["rowFilter.users.created_at"];
          nonce?: parameters["rowFilter.users.nonce"];
          id?: parameters["rowFilter.users.id"];
          name?: parameters["rowFilter.users.name"];
          updated_at?: parameters["rowFilter.users.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          public_address?: parameters["rowFilter.users.public_address"];
          created_at?: parameters["rowFilter.users.created_at"];
          nonce?: parameters["rowFilter.users.nonce"];
          id?: parameters["rowFilter.users.id"];
          name?: parameters["rowFilter.users.name"];
          updated_at?: parameters["rowFilter.users.updated_at"];
        };
        body: {
          /** users */
          users?: definitions["users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  activities: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: public.environment_enum
     * @enum {string}
     */
    environment: "PVP" | "PVE" | "REVIVE";
    /** Format: text */
    description: string;
    /** Format: numeric */
    amountOfPlayers: number;
    /** Format: ARRAY */
    activityWinner?: unknown[];
    /** Format: ARRAY */
    activityLoser?: unknown[];
    /** Format: ARRAY */
    killCounts?: unknown[];
  };
  /** @description Payout information for all completed games */
  payouts: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: character varying */
    public_address: string;
    /** Format: numeric */
    payment_amount: number;
    /** Format: character varying */
    payment_token_symbol: string;
    /** Format: character varying */
    payment_token_address: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `rooms.id`.<fk table='rooms' column='id'/>
     */
    room_id: string;
    /** Format: character varying */
    notes?: string;
    /** Format: character varying */
    reason: string;
  };
  /** @description Players in each room. */
  players: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `rooms.id`.<fk table='rooms' column='id'/>
     */
    room_id: string;
    /** Format: character varying */
    slug: string;
    /**
     * Format: character varying
     * @description Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `users.public_address`.<fk table='users' column='public_address'/>
     */
    player: string;
    /**
     * Format: timestamp without time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    time_joined: string;
  };
  /** @description Holds all parameters of each room */
  room_params: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: character varying
     * @description Public Address of creator
     *
     * Note:
     * This is a Foreign Key to `users.public_address`.<fk table='users' column='public_address'/>
     */
    created_by: string;
    /** Format: character varying */
    slug: string;
    /**
     * Format: character varying
     * @description Network rpc where contract lives
     */
    network: string;
    /**
     * Format: character varying
     * @description Address where the alt split rewards should be sent.
     */
    alt_split_address: string;
    /**
     * Format: character varying
     * @description Contract address of the payment token
     */
    contract_address: string;
    /**
     * Format: numeric
     * @description Token cost in order to enter the game
     */
    entry_fee: number;
    /**
     * Format: numeric
     * @description Chance that a PvE event will occur
     */
    pve_chance: number;
    /**
     * Format: numeric
     * @description Chance that a revive event will occur
     */
    revive_chance: number;
    /**
     * Format: numeric
     * @description Total prize split for kills in the game
     */
    prize_kills: number;
    /**
     * Format: numeric
     * @description Total prize split designated to go to the alternate address.
     */
    prize_alt_split: number;
    /**
     * Format: numeric
     * @description Total prize split for the game winner
     */
    prize_first: number;
    /**
     * Format: numeric
     * @description Total prize split for 2nd place
     */
    prize_second: number;
    /**
     * Format: numeric
     * @description Total prize split for third place
     */
    prize_third: number;
    /**
     * Format: numeric
     * @description Total prize split designated for the developers of Rumble Raffle
     */
    prize_creator: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at: string;
  };
  /** @description Available rooms to join. */
  rooms: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: text
     * @description The room slug
     */
    slug: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `room_params.id`.<fk table='room_params' column='id'/>
     */
    params_id: string;
    /**
     * Format: character varying
     * @description Note:
     * This is a Foreign Key to `users.public_address`.<fk table='users' column='public_address'/>
     */
    created_by: string;
    /** Format: boolean */
    game_started: boolean;
  };
  /** @description Users that have logged into the app */
  users: {
    /**
     * Format: character varying
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    public_address: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: character varying */
    nonce: string;
    /**
     * Format: uuid
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /** Format: text */
    name: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    updated_at: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description activities */
  "body.activities": definitions["activities"];
  /** Format: uuid */
  "rowFilter.activities.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.activities.created_at": string;
  /** Format: public.environment_enum */
  "rowFilter.activities.environment": string;
  /** Format: text */
  "rowFilter.activities.description": string;
  /** Format: numeric */
  "rowFilter.activities.amountOfPlayers": string;
  /** Format: ARRAY */
  "rowFilter.activities.activityWinner": string;
  /** Format: ARRAY */
  "rowFilter.activities.activityLoser": string;
  /** Format: ARRAY */
  "rowFilter.activities.killCounts": string;
  /** @description payouts */
  "body.payouts": definitions["payouts"];
  /** Format: uuid */
  "rowFilter.payouts.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.payouts.created_at": string;
  /** Format: character varying */
  "rowFilter.payouts.public_address": string;
  /** Format: numeric */
  "rowFilter.payouts.payment_amount": string;
  /** Format: character varying */
  "rowFilter.payouts.payment_token_symbol": string;
  /** Format: character varying */
  "rowFilter.payouts.payment_token_address": string;
  /** Format: uuid */
  "rowFilter.payouts.room_id": string;
  /** Format: character varying */
  "rowFilter.payouts.notes": string;
  /** Format: character varying */
  "rowFilter.payouts.reason": string;
  /** @description players */
  "body.players": definitions["players"];
  /** Format: uuid */
  "rowFilter.players.room_id": string;
  /** Format: character varying */
  "rowFilter.players.slug": string;
  /** Format: character varying */
  "rowFilter.players.player": string;
  /** Format: timestamp without time zone */
  "rowFilter.players.time_joined": string;
  /** @description room_params */
  "body.room_params": definitions["room_params"];
  /** Format: uuid */
  "rowFilter.room_params.id": string;
  /**
   * Format: character varying
   * @description Public Address of creator
   */
  "rowFilter.room_params.created_by": string;
  /** Format: character varying */
  "rowFilter.room_params.slug": string;
  /**
   * Format: character varying
   * @description Network rpc where contract lives
   */
  "rowFilter.room_params.network": string;
  /**
   * Format: character varying
   * @description Address where the alt split rewards should be sent.
   */
  "rowFilter.room_params.alt_split_address": string;
  /**
   * Format: character varying
   * @description Contract address of the payment token
   */
  "rowFilter.room_params.contract_address": string;
  /**
   * Format: numeric
   * @description Token cost in order to enter the game
   */
  "rowFilter.room_params.entry_fee": string;
  /**
   * Format: numeric
   * @description Chance that a PvE event will occur
   */
  "rowFilter.room_params.pve_chance": string;
  /**
   * Format: numeric
   * @description Chance that a revive event will occur
   */
  "rowFilter.room_params.revive_chance": string;
  /**
   * Format: numeric
   * @description Total prize split for kills in the game
   */
  "rowFilter.room_params.prize_kills": string;
  /**
   * Format: numeric
   * @description Total prize split designated to go to the alternate address.
   */
  "rowFilter.room_params.prize_alt_split": string;
  /**
   * Format: numeric
   * @description Total prize split for the game winner
   */
  "rowFilter.room_params.prize_first": string;
  /**
   * Format: numeric
   * @description Total prize split for 2nd place
   */
  "rowFilter.room_params.prize_second": string;
  /**
   * Format: numeric
   * @description Total prize split for third place
   */
  "rowFilter.room_params.prize_third": string;
  /**
   * Format: numeric
   * @description Total prize split designated for the developers of Rumble Raffle
   */
  "rowFilter.room_params.prize_creator": string;
  /** Format: timestamp with time zone */
  "rowFilter.room_params.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.room_params.updated_at": string;
  /** @description rooms */
  "body.rooms": definitions["rooms"];
  /** Format: uuid */
  "rowFilter.rooms.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.rooms.created_at": string;
  /**
   * Format: text
   * @description The room slug
   */
  "rowFilter.rooms.slug": string;
  /** Format: uuid */
  "rowFilter.rooms.params_id": string;
  /** Format: character varying */
  "rowFilter.rooms.created_by": string;
  /** Format: boolean */
  "rowFilter.rooms.game_started": string;
  /** @description users */
  "body.users": definitions["users"];
  /** Format: character varying */
  "rowFilter.users.public_address": string;
  /** Format: timestamp with time zone */
  "rowFilter.users.created_at": string;
  /** Format: character varying */
  "rowFilter.users.nonce": string;
  /** Format: uuid */
  "rowFilter.users.id": string;
  /** Format: text */
  "rowFilter.users.name": string;
  /** Format: timestamp with time zone */
  "rowFilter.users.updated_at": string;
}

export interface operations {}

export interface external {}
