import Head from 'next/head'
import { withSessionSsr } from '../lib/with-session'
import { WalletProvider } from '../containers/wallet'

/**
 * TODO:
 * - Better error handling on client side so when errors happen we don't blow up the app.
 */

const pageTitle = `Rumble Raffle DAO`
export default function PageIndex(props) {
  return (
    <div>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WalletProvider initialState={props.user}>
        <div>Home Page</div>
      </WalletProvider>
    </div>
  )
}

export const getServerSideProps = withSessionSsr(({ req }) => {
  const user = req?.session?.user
  return {
    props: {
      ...(user && { user })
    }
  }
})